# Generated by Django 5.2.1 on 2025-06-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_service_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
