# Generated by Django 5.2 on 2025-04-23 12:34

import apps.users.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(help_text='Número de 10 dígitos sin prefijo (ej: 3001234567).', max_length=10, validators=[apps.users.validators.validate_10_digits])),
                ('opening_time', models.TimeField(default='08:00:00', verbose_name='Hora de apertura')),
                ('closing_time', models.TimeField(default='18:00:00', verbose_name='Hora de cierre')),
                ('available_days', models.CharField(default='0,1,2,3,4,5', help_text='Días laborales separados por comas (0=Lunes, 6=Domingo).', max_length=13)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.city')),
            ],
        ),
    ]
