# Generated by Django 5.2.1 on 2025-06-12 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_category_location_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='name_business',
        ),
    ]
