# Generated by Django 5.2.1 on 2025-06-16 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_rename_name_location_name_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='phone',
            new_name='phone_business',
        ),
    ]
