# Generated by Django 5.2.1 on 2025-06-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='user',
            name='active_role',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Client', 'Client'), ('Professional', 'Professional')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='identification',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
