# Generated by Django 5.2.1 on 2025-06-04 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_roles_remove_user_active_role_user_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='identification',
        ),
    ]
